# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b51311cf15e7cf81f7c6de69ff3a594a169fc6264c7f97254408c0511a83d25d5d8efe3dc9b3b303aa3b33a8b6929c8e7be6ef9e7a62acc2c5e15a2cb01dfd5

test:
  secret_key_base: e0da4e3db75eee5ad762d112c4f7c2e7a3c6ae49fba07935c1cee6014855d31bef8fa64ffe88adea00a71f9998387f8c925d2ade1d066dfb9a6e80deabf776dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
